# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'abc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for abc

  target 'abc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'abcTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'abc-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for abc-tvOS

  target 'abc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
